name: First GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print confirmation message
        run: echo "My first GitHub Actions workflow ran successfully."
